name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: echo "Event     = ${{ github.event_name }}
                   Runner    = ${{ runner.os }}
                   Repo      = ${{ github.repository }}
                   Branch    = ${{ github.ref }}
                   Workspace = ${{ github.workspace }}
                   Status    = ${{ job.status }}"

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: echo "Build successful 🎉 🚀"