name: PullRequest-Builder
run-name: "Triggered by ${{ github.event_name }} event to ${{ github.ref }}. Author: ${{ github.actor }}"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  PullRequest-Builder:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
    steps:
      - run: echo "Runner=${{ runner.os }}, Repo=${{ github.repository }}, Branch=${{ github.ref }}, Workspace=${{ github.workspace }}"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - run: echo "Build successful 🎉 🚀"