name: PullRequest-Builder
run-name: "Triggered by ${{ github.event_name }} event to ${{ github.ref }}. Author: ${{ github.actor }}"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read
  packages: write

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  PullRequest-Builder:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "Runner=${{ runner.os }}, Repo=${{ github.repository }}, Branch=${{ github.ref }}, Workspace=${{ github.workspace }}"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - run: echo "Build successful 🎉 🚀"

  Build-And-Publish-Docker-Image:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: PullRequest-Builder
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            abidfs/nextjs-template:latest
            abidfs/nextjs-template:1.0.0
            ghcr.io/abidfs/nextjs-template:latest
            ghcr.io/abidfs/nextjs-template:1.0.0
